# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/misza/studia/2sem/IPP/duzy projekt/gamma"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/misza/studia/2sem/IPP/duzy projekt/gamma"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/misza/studia/2sem/IPP/duzy projekt/gamma/CMakeFiles" "/home/misza/studia/2sem/IPP/duzy projekt/gamma/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/misza/studia/2sem/IPP/duzy projekt/gamma/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

src/UI/batch_mode/batch-mode.o: src/UI/batch_mode/batch-mode.c.o

.PHONY : src/UI/batch_mode/batch-mode.o

# target to build an object file
src/UI/batch_mode/batch-mode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/batch_mode/batch-mode.c.o
.PHONY : src/UI/batch_mode/batch-mode.c.o

src/UI/batch_mode/batch-mode.i: src/UI/batch_mode/batch-mode.c.i

.PHONY : src/UI/batch_mode/batch-mode.i

# target to preprocess a source file
src/UI/batch_mode/batch-mode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/batch_mode/batch-mode.c.i
.PHONY : src/UI/batch_mode/batch-mode.c.i

src/UI/batch_mode/batch-mode.s: src/UI/batch_mode/batch-mode.c.s

.PHONY : src/UI/batch_mode/batch-mode.s

# target to generate assembly for a file
src/UI/batch_mode/batch-mode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/batch_mode/batch-mode.c.s
.PHONY : src/UI/batch_mode/batch-mode.c.s

src/UI/error-handling.o: src/UI/error-handling.c.o

.PHONY : src/UI/error-handling.o

# target to build an object file
src/UI/error-handling.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/error-handling.c.o
.PHONY : src/UI/error-handling.c.o

src/UI/error-handling.i: src/UI/error-handling.c.i

.PHONY : src/UI/error-handling.i

# target to preprocess a source file
src/UI/error-handling.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/error-handling.c.i
.PHONY : src/UI/error-handling.c.i

src/UI/error-handling.s: src/UI/error-handling.c.s

.PHONY : src/UI/error-handling.s

# target to generate assembly for a file
src/UI/error-handling.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/error-handling.c.s
.PHONY : src/UI/error-handling.c.s

src/UI/interactive_mode/interactive-mode.o: src/UI/interactive_mode/interactive-mode.c.o

.PHONY : src/UI/interactive_mode/interactive-mode.o

# target to build an object file
src/UI/interactive_mode/interactive-mode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/interactive_mode/interactive-mode.c.o
.PHONY : src/UI/interactive_mode/interactive-mode.c.o

src/UI/interactive_mode/interactive-mode.i: src/UI/interactive_mode/interactive-mode.c.i

.PHONY : src/UI/interactive_mode/interactive-mode.i

# target to preprocess a source file
src/UI/interactive_mode/interactive-mode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/interactive_mode/interactive-mode.c.i
.PHONY : src/UI/interactive_mode/interactive-mode.c.i

src/UI/interactive_mode/interactive-mode.s: src/UI/interactive_mode/interactive-mode.c.s

.PHONY : src/UI/interactive_mode/interactive-mode.s

# target to generate assembly for a file
src/UI/interactive_mode/interactive-mode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/interactive_mode/interactive-mode.c.s
.PHONY : src/UI/interactive_mode/interactive-mode.c.s

src/UI/text_lib/strings.o: src/UI/text_lib/strings.c.o

.PHONY : src/UI/text_lib/strings.o

# target to build an object file
src/UI/text_lib/strings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/UI/text_lib/strings.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/text_lib/strings.c.o
.PHONY : src/UI/text_lib/strings.c.o

src/UI/text_lib/strings.i: src/UI/text_lib/strings.c.i

.PHONY : src/UI/text_lib/strings.i

# target to preprocess a source file
src/UI/text_lib/strings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/UI/text_lib/strings.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/text_lib/strings.c.i
.PHONY : src/UI/text_lib/strings.c.i

src/UI/text_lib/strings.s: src/UI/text_lib/strings.c.s

.PHONY : src/UI/text_lib/strings.s

# target to generate assembly for a file
src/UI/text_lib/strings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/UI/text_lib/strings.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/UI/text_lib/strings.c.s
.PHONY : src/UI/text_lib/strings.c.s

src/game_engine/find-union.o: src/game_engine/find-union.c.o

.PHONY : src/game_engine/find-union.o

# target to build an object file
src/game_engine/find-union.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/find-union.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/find-union.c.o
.PHONY : src/game_engine/find-union.c.o

src/game_engine/find-union.i: src/game_engine/find-union.c.i

.PHONY : src/game_engine/find-union.i

# target to preprocess a source file
src/game_engine/find-union.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/find-union.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/find-union.c.i
.PHONY : src/game_engine/find-union.c.i

src/game_engine/find-union.s: src/game_engine/find-union.c.s

.PHONY : src/game_engine/find-union.s

# target to generate assembly for a file
src/game_engine/find-union.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/find-union.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/find-union.c.s
.PHONY : src/game_engine/find-union.c.s

src/game_engine/gamma-delete.o: src/game_engine/gamma-delete.c.o

.PHONY : src/game_engine/gamma-delete.o

# target to build an object file
src/game_engine/gamma-delete.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-delete.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-delete.c.o
.PHONY : src/game_engine/gamma-delete.c.o

src/game_engine/gamma-delete.i: src/game_engine/gamma-delete.c.i

.PHONY : src/game_engine/gamma-delete.i

# target to preprocess a source file
src/game_engine/gamma-delete.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-delete.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-delete.c.i
.PHONY : src/game_engine/gamma-delete.c.i

src/game_engine/gamma-delete.s: src/game_engine/gamma-delete.c.s

.PHONY : src/game_engine/gamma-delete.s

# target to generate assembly for a file
src/game_engine/gamma-delete.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-delete.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-delete.c.s
.PHONY : src/game_engine/gamma-delete.c.s

src/game_engine/gamma-moves-assistant-functions.o: src/game_engine/gamma-moves-assistant-functions.c.o

.PHONY : src/game_engine/gamma-moves-assistant-functions.o

# target to build an object file
src/game_engine/gamma-moves-assistant-functions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-moves-assistant-functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-moves-assistant-functions.c.o
.PHONY : src/game_engine/gamma-moves-assistant-functions.c.o

src/game_engine/gamma-moves-assistant-functions.i: src/game_engine/gamma-moves-assistant-functions.c.i

.PHONY : src/game_engine/gamma-moves-assistant-functions.i

# target to preprocess a source file
src/game_engine/gamma-moves-assistant-functions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-moves-assistant-functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-moves-assistant-functions.c.i
.PHONY : src/game_engine/gamma-moves-assistant-functions.c.i

src/game_engine/gamma-moves-assistant-functions.s: src/game_engine/gamma-moves-assistant-functions.c.s

.PHONY : src/game_engine/gamma-moves-assistant-functions.s

# target to generate assembly for a file
src/game_engine/gamma-moves-assistant-functions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma-moves-assistant-functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma-moves-assistant-functions.c.s
.PHONY : src/game_engine/gamma-moves-assistant-functions.c.s

src/game_engine/gamma.o: src/game_engine/gamma.c.o

.PHONY : src/game_engine/gamma.o

# target to build an object file
src/game_engine/gamma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma.c.o
.PHONY : src/game_engine/gamma.c.o

src/game_engine/gamma.i: src/game_engine/gamma.c.i

.PHONY : src/game_engine/gamma.i

# target to preprocess a source file
src/game_engine/gamma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma.c.i
.PHONY : src/game_engine/gamma.c.i

src/game_engine/gamma.s: src/game_engine/gamma.c.s

.PHONY : src/game_engine/gamma.s

# target to generate assembly for a file
src/game_engine/gamma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/game_engine/gamma.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/game_engine/gamma.c.s
.PHONY : src/game_engine/gamma.c.s

src/gamma-launch.o: src/gamma-launch.c.o

.PHONY : src/gamma-launch.o

# target to build an object file
src/gamma-launch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma-launch.c.o
.PHONY : src/gamma-launch.c.o

src/gamma-launch.i: src/gamma-launch.c.i

.PHONY : src/gamma-launch.i

# target to preprocess a source file
src/gamma-launch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma-launch.c.i
.PHONY : src/gamma-launch.c.i

src/gamma-launch.s: src/gamma-launch.c.s

.PHONY : src/gamma-launch.s

# target to generate assembly for a file
src/gamma-launch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma-launch.c.s
.PHONY : src/gamma-launch.c.s

src/gamma_main.o: src/gamma_main.c.o

.PHONY : src/gamma_main.o

# target to build an object file
src/gamma_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma_main.c.o
.PHONY : src/gamma_main.c.o

src/gamma_main.i: src/gamma_main.c.i

.PHONY : src/gamma_main.i

# target to preprocess a source file
src/gamma_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma_main.c.i
.PHONY : src/gamma_main.c.i

src/gamma_main.s: src/gamma_main.c.s

.PHONY : src/gamma_main.s

# target to generate assembly for a file
src/gamma_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamma.dir/build.make CMakeFiles/gamma.dir/src/gamma_main.c.s
.PHONY : src/gamma_main.c.s

src/gamma_test.o: src/gamma_test.c.o

.PHONY : src/gamma_test.o

# target to build an object file
src/gamma_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/gamma_test.c.o
.PHONY : src/gamma_test.c.o

src/gamma_test.i: src/gamma_test.c.i

.PHONY : src/gamma_test.i

# target to preprocess a source file
src/gamma_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/gamma_test.c.i
.PHONY : src/gamma_test.c.i

src/gamma_test.s: src/gamma_test.c.s

.PHONY : src/gamma_test.s

# target to generate assembly for a file
src/gamma_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/gamma_test.c.s
.PHONY : src/gamma_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... gamma"
	@echo "... test"
	@echo "... src/UI/batch_mode/batch-mode.o"
	@echo "... src/UI/batch_mode/batch-mode.i"
	@echo "... src/UI/batch_mode/batch-mode.s"
	@echo "... src/UI/error-handling.o"
	@echo "... src/UI/error-handling.i"
	@echo "... src/UI/error-handling.s"
	@echo "... src/UI/interactive_mode/interactive-mode.o"
	@echo "... src/UI/interactive_mode/interactive-mode.i"
	@echo "... src/UI/interactive_mode/interactive-mode.s"
	@echo "... src/UI/text_lib/strings.o"
	@echo "... src/UI/text_lib/strings.i"
	@echo "... src/UI/text_lib/strings.s"
	@echo "... src/game_engine/find-union.o"
	@echo "... src/game_engine/find-union.i"
	@echo "... src/game_engine/find-union.s"
	@echo "... src/game_engine/gamma-delete.o"
	@echo "... src/game_engine/gamma-delete.i"
	@echo "... src/game_engine/gamma-delete.s"
	@echo "... src/game_engine/gamma-moves-assistant-functions.o"
	@echo "... src/game_engine/gamma-moves-assistant-functions.i"
	@echo "... src/game_engine/gamma-moves-assistant-functions.s"
	@echo "... src/game_engine/gamma.o"
	@echo "... src/game_engine/gamma.i"
	@echo "... src/game_engine/gamma.s"
	@echo "... src/gamma-launch.o"
	@echo "... src/gamma-launch.i"
	@echo "... src/gamma-launch.s"
	@echo "... src/gamma_main.o"
	@echo "... src/gamma_main.i"
	@echo "... src/gamma_main.s"
	@echo "... src/gamma_test.o"
	@echo "... src/gamma_test.i"
	@echo "... src/gamma_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

