var menudata={children:[
{text:"Strona główna",url:"index.html"},
{text:"Struktury Danych",url:"annotated.html",children:[
{text:"Struktury danych",url:"annotated.html"},
{text:"Indeks struktur danych",url:"classes.html"},
{text:"Pola danych",url:"functions.html",children:[
{text:"Wszystko",url:"functions.html"},
{text:"Zmienne",url:"functions_vars.html"}]}]},
{text:"Pliki",url:"files.html",children:[
{text:"Lista plików",url:"files.html"},
{text:"Globalne",url:"globals.html",children:[
{text:"Wszystko",url:"globals.html",children:[
{text:"_",url:"globals.html#index__"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"g",url:"globals.html#index_g"},
{text:"h",url:"globals.html#index_h"},
{text:"i",url:"globals.html#index_i"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"n",url:"globals.html#index_n"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"u",url:"globals.html#index_u"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"},
{text:"x",url:"globals.html#index_x"},
{text:"y",url:"globals.html#index_y"}]},
{text:"Funkcje",url:"globals_func.html",children:[
{text:"b",url:"globals_func.html#index_b"},
{text:"c",url:"globals_func.html#index_c"},
{text:"e",url:"globals_func.html#index_e"},
{text:"f",url:"globals_func.html#index_f"},
{text:"g",url:"globals_func.html#index_g"},
{text:"i",url:"globals_func.html#index_i"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"r",url:"globals_func.html#index_r"},
{text:"s",url:"globals_func.html#index_s"},
{text:"u",url:"globals_func.html#index_u"},
{text:"v",url:"globals_func.html#index_v"}]},
{text:"Zmienne",url:"globals_vars.html"},
{text:"Definicje typów",url:"globals_type.html"},
{text:"Wyliczenia",url:"globals_enum.html"},
{text:"Definicje",url:"globals_defs.html"}]}]}]}
